# Generated by Django 4.2.6 on 2023-10-04 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trivias', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trivia',
            name='fecha',
            field=models.DateTimeField(verbose_name='fecha de publicación'),
        ),
    ]
