# Generated by Django 4.2.6 on 2023-10-04 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trivias', '0002_alter_trivia_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trivia',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación'),
        ),
    ]
