# Generated by Django 4.2.6 on 2023-10-04 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trivias', '0003_alter_trivia_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='trivia',
            name='titulo',
            field=models.CharField(default='default', max_length=200),
            preserve_default=False,
        ),
    ]
