# Generated by Django 4.2.6 on 2023-10-05 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preguntas', '0004_alter_pregunta_fecha_publicacion'),
        ('trivias', '0004_trivia_titulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='trivia',
            name='preguntas',
            field=models.ManyToManyField(related_name='trivias', to='preguntas.pregunta'),
        ),
    ]
