# Generated by Django 4.2.6 on 2023-10-04 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preguntas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pregunta',
            name='fecha_categoria',
            field=models.DateField(blank=True, null=True, verbose_name='fecha de categoría'),
        ),
    ]
