# Generated by Django 4.2.6 on 2023-10-04 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preguntas', '0003_remove_pregunta_fecha_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pregunta',
            name='fecha_publicacion',
            field=models.DateTimeField(blank=True, null=True, verbose_name='fecha de publicación'),
        ),
    ]
