# Generated by Django 4.2.6 on 2023-10-05 01:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('preguntas', '0006_alter_respuesta_pregunta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='respuesta',
            name='pregunta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='preguntas.pregunta'),
        ),
    ]
